# Generated by Django 5.1.3 on 2024-11-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='Category',
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='products.category'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
