# Generated by Django 5.1.3 on 2024-11-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
