# Generated by Django 5.1.3 on 2024-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_is_listd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(null=True),
        ),
    ]
