# Generated by Django 5.1.3 on 2024-11-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_varient_product_id_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_listed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
