# Generated by Django 5.1.3 on 2024-11-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_listed_variant_is_listed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_listd',
            new_name='is_listed',
        ),
    ]
