# Generated by Django 5.1.3 on 2024-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default=True, null=True),
        ),
    ]
