# Generated by Django 5.1.3 on 2024-12-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_subcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='is_listed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
