# Generated by Django 4.2.7 on 2026-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_coupon_price_order_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failure', 'Failure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'cash on delivery'), ('RazorPay', 'Razor Pay'), ('wallet', 'wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Pending'), ('Confirmed', ' Order Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Requested Return', 'Requested Return'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
