# Generated by Django 5.1.3 on 2024-12-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_offer',
            old_name='Brand',
            new_name='brand',
        ),
    ]
