# Generated by Django 5.1.3 on 2024-12-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_rename_brand_brand_offer_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand_offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product_offer',
            options={'ordering': ['-created_at']},
        ),
    ]
