# Generated by Django 4.2.7 on 2026-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_rename_offer_price_brand_offer_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_offer',
            name='offer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
