# Generated by Django 5.1.3 on 2024-12-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='detail_address',
        ),
    ]
