# Generated by Django 5.1.3 on 2024-12-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_user_couponusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponusage',
            old_name='user_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
